### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by louis70109** [louis70109/LINE-subscribe-open-data-bot#1]
- [x] LINE Notify
- [x] flask view template
- [x] LIFF share target picker
- [x] Heroku Procfile and app.json
- [x] crontab
- [x] update README postgresql section.
